CREATE TABLE reservations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id          BIGINT NOT NULL,
    user_id          BIGINT NOT NULL,
    reservation_date DATE   NOT NULL,
    CONSTRAINT fk_reservations_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_reservations_user FOREIGN KEY (user_id) REFERENCES users (id)
);